name: Complete Installation
on: 
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Complete Installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Full Installation
        run: |
          chmod +x full.sh
          sudo ./full.sh
      
      - name: Test Installed Apps
        run: |
          gcc -v
          make -v
          terraform -v
          go version
          # java -version
          # javac -version
          mvn -version
          # nvm --version
          GVM_ROOT=$HOME/.gvm ~/.gvm/bin/gvm version
          hasura version