name: Complete Installation
on: 
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test init.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
          chmod +x init.sh
          sudo ./init.sh
      
      - name: Test Installed Apps
        run: |
          terraform -v