name: Complete Installation
on: 
  push:
    branches:
      - master
jobs:
  test:
    name: Test init.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test
        run: |
          ./init.sh