name: Complete Installation
on: 
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test init.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test
        run: |
          ./init.sh