name: Partial Installation
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Partial Installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: init.sh
        run: |
          chmod +x init.sh
          sudo ./init.sh
          gcc -v
          make -v
      
      - name: Terraform
        run: |
          make terraform
          terraform -v
      
      - name: GVM
        run: |
          make gvm
          GVM_ROOT=$HOME/.gvm ~/.gvm/bin/gvm version
      
      - name: Java
        run: |
          make java
          # java -version
          # javac -version
      
      - name: Maven
        run: |
          make maven
          mvn -version
      
      - name: NVM
        run: |
          make nvm
          # nvm --version
      
      - name: Hasura
        run: |
          make hasura
          hasura version
