name: Partial Installation
on: 
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Partial Installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test init.sh
        run: |
          chmod +x init.sh
          sudo ./init.sh
      
      - name: Verify init.sh
        run: |
          gcc -v
          make -v
      
      - name: Test Terraform
        run: |
          make terraform
      
      - name: Verify Terraform
        run: |
          terraform -v
      
      - name: Test GoLang
        run: |
          make golang
      
      - name: Verify GoLang
        run: |
          go version
      
      - name: Test Java
        run: |
          make java
      
      # - name: Verify Java
      #   run: |
      #     java -version
      #     javac -version
      
      - name: Test Maven
        run: |
          make maven
      
      - name: Verify Maven
        run: |
          mvn -version
      
      - name: Test NVM
        run: |
          make nvm
      
      - name: Verify NVM
        run: |
          nvm --version
