name: Complete Installation
on: 
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Partially
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test init.sh
        run: |
          chmod +x init.sh
          sudo ./init.sh
      
      - name: Verify init.sh
        run: |
          make -v
      
      - name: Test Terraform
        run: |
          make terraform
      
      - name: Verify Terraform
        run: |
          terraform -v